### ISSUE TITLE
gh-upload.py post hook is stalling 

### ISSUE THREAD

**Issue by necrose99** [necrose99/gentoo-binhost#1]
needs fixing or sticks on console
@spreequalle i need to ask ,

**Comment by necrose99** [comment]
could be a mix of recoved packages / and revdep-rebuils upgrade world and or space on EMMC stalling. /exhausted ..  hence why i really need a binhost to push too. and alow for further collaboration.

**Comment by necrose99** [comment]
gh_branch = os.environ['CHOST'] # use chost as git branch name

much to my irk the makefile it seams if _generic unknown arm64 gnu_ 

how to vanity-ize the chost w/o busting shit.... @spreequalle 
suggestions welcome atm 

trying to get @mudler & @geaaru 's little dev ops goodies on rpi3 docker/helm etc then leave with weekly genup ala sakaki-  repos 
RPI3 isnt wholly powerful but as a worker bee @ home discc/docker-cluster  for arm64 
its just a compute node at this point.. for sub worker tasks. 

so it cares alot for chost in GCC settings . rock64  drive is maxed on eemc till i get a new rock64 /bsd /freenas or other means of not being to the roof in bins..

**Comment by necrose99** [comment]
@spreequalle 
gh_branch_overide=[force chost=github branch] might be a plus i'vent rebuilt a custom GCC.

**Comment by spreequalle** [comment]
Yeah i switched chost for every binhost environment, the idea was to have optimized binaries for them,

You can just switch gh_branch to your release branch if you don’t want to go that route.

 

e.g.

gh_branch = master

 

best regards,

erik

 

Von: "Michael L." <notifications@github.com>
Antworten an: necrose99/gentoo-binhost <reply@reply.github.com>
Datum: Sonntag, 23. Februar 2020 um 02:35
An: necrose99/gentoo-binhost <gentoo-binhost@noreply.github.com>
Cc: Spreequalle <ErikHoppe@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [necrose99/gentoo-binhost] gh-upload.py post hook is stalling (#1)

 

gh_branch = os.environ['CHOST'] # use chost as git branch name

much to my irk the makefile it seams if generic unknown arm64 gnu

how to vanity-ize the chost w/o busting shit.... @spreequalle
suggestions welcome atm

trying to get @mudler & @geaaru 's little dev ops goodies on rpi3 docker/helm etc then leave with weekly genup ala sakaki- repos
RPI3 isnt wholly powerful but as a worker bee @ home discc/docker-cluster for arm64
its just a compute node at this point.. for sub worker tasks.

so it cares alot for chost in GCC settings . rock64 drive is maxed on eemc till i get a new rock64 /bsd /freenas or other means of not being to the roof in bins..

**Comment by necrose99** [comment]
@spreequalle  https://github.com/sakaki-/gentoo-on-rpi-64bit  
@sakaki- they have the base vanilla Generic from stage3 , 
till i get a new emmc or m2 for rockpro-64 doing any hand twaek building in on rpi3  ,or bins archived off.  
may just get a BSD-load nas box/freenas  and put sshfs:/gentoo/repos ,distfiles  /packages on nas 
 
pinebook-pro looks fun , and can hide a few more harkrf toys inside etc.. and 200 ish not hining ,
gh_branch = should do 
@ZeroChaos-  for 5 lousy bucks mo. per 50 gig of lfs .vs vps n cloud hosting some are better n others.  ... worth giving a run @Pentoo
**x86_64-Pentoo-hardened-linux-gnu** branch/etc and since github global mirrors 

once i get kinks out can have a spare mirror , and open vps for arm64  etc.

**Comment by necrose99** [comment]
Praise Odin bins are psting now,.. :-) 
now to get chost more tweaked.
